Temporal: removed $system* query options
oasis-tcs/odata-abnf pull request #33
Opened 2021-05-07 12:13 UTC by ralfhandl

2021-05-07 13:46 UTC, HeikoTheissen reviewed
How do these test cases work?

2021-05-07 13:57 UTC, ralfhandl commented
On Windows follow the instructions in https://github.com/oasis-tcs/odata-abnf/tree/master/tools/PowerShell.

If you use VS Code, then use the "Check ABNF & watch" task: whenever you save a changed ABNF or test case file, the ABNF is automatically compiled and all tests are executed.

2021-05-07 14:33 UTC, HeikoTheissen approved these changes

2021-05-07 14:58 UTC, ralfhandl commented on abnf/odata-temporal-testcases.xml
> +  <Constraint Rule="streamProperty" />
Try removing it and see what happens 😁

Explanation: without this $expand=Department etc. would be interpreted as expanding a stream property by the parser.

2021-05-26 10:14 UTC, HeikoTheissen requested changes
Test case for $toInclusive with timestamp

2021-05-26 10:14 UTC, HeikoTheissen commented on abnf/odata-temporal-testcases.xml
>    </TestCase>
```suggestion
  <TestCase Name="Temporal - from and to with datetimestamp" Rule="odataRelativeUri">
    <Input>Employees?$from=2012-07-26T09:00:00.00-08:00&amp;$to=2012-07-26T11:00:00.00-08:00</Input>
  </TestCase>
  <TestCase Name="Temporal - from and toInclusive with datetimestamp" Rule="odataRelativeUri">
    <Input>Employees?$from=2012-07-26T09:00:00.00-08:00&amp;$toInclusive=2012-07-26T11:00:00.00-08:00</Input>
  </TestCase>
```

2021-05-26 10:26 UTC, HeikoTheissen approved these changes

2021-07-22 15:31 UTC, merged